### ISSUE TITLE
ToDo: Player Turn 

### ISSUE THREAD

**Issue by misslame** [misslame/BattleShipAIBUTTS#3]
Current standing as of 10/4:
  
- [x] The application prepares for player turn but has 0 implementations for it. 
- [x] This also need AI to initialize their board in just after the player successfully hits "confirm placement"
- [x] Reinitialize window with player board & enemy board

**Comment by misslame** [comment]
Completed with recent push
